# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: apigateway
 

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
    
zuul:
  routes:
    user:
      path: /zuuluser/**
      serviceId: UserService
    note:
      path: /zuulnote/**
      serviceId: NoteService
    sensitive-Headers: userId

server:
  port: 8080
 
ribbon:
       ConnectTimeout: 40000
       ReadTimeout: 40000

hystrix:
  threadpool:
    default:
      coreSize: 50000
      maximumSize: 50000
      queueSizeRejectionThreshold: -1
      maxQueueSize: -1
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
              timeoutInMilliseconds: 50000


  host:
    max-total-connections: 10000
    max-per-route-connections: 50


  
 
   
